package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptShape, myConceptSquare);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0x39f83b0be9bf414bL, 0x81a1ecf861c68cb6L, 0x26751e512ed1f83aL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ae6d78f1-dd83-458f-b071-218cfc54f0d7(Shapes.structure)/2771154479743105082");
    b.version(3);
    b.aggregate("shapes", 0x7aa1edc861980e56L).target(0x39f83b0be9bf414bL, 0x81a1ecf861c68cb6L, 0x26751e512ed1f82dL).optional(true).ordered(true).multiple(true).origin("8836605388764221014").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0x39f83b0be9bf414bL, 0x81a1ecf861c68cb6L, 0x26751e512ed1f82fL);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0x39f83b0be9bf414bL, 0x81a1ecf861c68cb6L, 0x26751e512ed1f82dL);
    b.origin("r:ae6d78f1-dd83-458f-b071-218cfc54f0d7(Shapes.structure)/2771154479743105071");
    b.version(3);
    b.property("x", 0x26751e512ed1f831L).type(PrimitiveTypeId.INTEGER).origin("2771154479743105073").done();
    b.property("y", 0x26751e512ed1f832L).type(PrimitiveTypeId.INTEGER).origin("2771154479743105074").done();
    b.property("radio", 0x26751e512ed1f833L).type(PrimitiveTypeId.INTEGER).origin("2771154479743105075").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shape", 0x39f83b0be9bf414bL, 0x81a1ecf861c68cb6L, 0x26751e512ed1f82dL);
    b.class_(false, true, false);
    b.origin("r:ae6d78f1-dd83-458f-b071-218cfc54f0d7(Shapes.structure)/2771154479743105069");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0x39f83b0be9bf414bL, 0x81a1ecf861c68cb6L, 0x26751e512ed1f836L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0x39f83b0be9bf414bL, 0x81a1ecf861c68cb6L, 0x26751e512ed1f82dL);
    b.origin("r:ae6d78f1-dd83-458f-b071-218cfc54f0d7(Shapes.structure)/2771154479743105078");
    b.version(3);
    b.property("upperLeftX", 0x26751e512ed1f837L).type(PrimitiveTypeId.INTEGER).origin("2771154479743105079").done();
    b.property("upperLeftY", 0x26751e512ed1f838L).type(PrimitiveTypeId.INTEGER).origin("2771154479743105080").done();
    b.property("size", 0x26751e512ed1f839L).type(PrimitiveTypeId.INTEGER).origin("2771154479743105081").done();
    b.alias("square");
    return b.create();
  }
}
