package Shapes.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;

public class MyDrawing extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      graphics.setColor(Color.blue);
      graphics.drawOval(190, 250, 60, 60);
      graphics.setColor(Color.green);
      graphics.drawRect(140, 150, 60, 60);
      graphics.setColor(Color.green);
      graphics.drawRect(240, 150, 60, 60);
      graphics.setColor(Color.red);
      graphics.drawRect(100, 100, 250, 250);
      {
        graphics.setColor(Color.blue);
        int[] xpoints = {250, 200, 225};
        int[] ypoints = {240, 240, 180};
        graphics.drawPolygon(xpoints, ypoints, 3);
      }
    }
  };

  private void initialize() {
    this.setTitle("MyDrawing");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }

  public static void main(String[] args) {
    MyDrawing canvas = new MyDrawing();
    canvas.initialize();
  }
}
